version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "09:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: rector/rector-prefixed
    versions:
    - 0.10.11
    - 0.10.3
    - 0.10.4
    - 0.10.6
    - 0.10.9
  - dependency-name: phpstan/phpstan
    versions:
    - 0.12.82
    - 0.12.83
    - 0.12.84
  - dependency-name: friendsofphp/php-cs-fixer
    versions:
    - 2.16.10
    - 2.18.4
    - 2.18.5
  - dependency-name: filp/whoops
    versions:
    - 2.10.0
    - 2.11.0
    - 2.12.0
    - 2.9.2
  - dependency-name: vimeo/psalm
    versions:
    - 4.6.4
    - 4.7.0
  - dependency-name: pestphp/pest
    versions:
    - 1.0.4
  - dependency-name: symfony/yaml
    versions:
    - 5.2.2
    - 5.2.3
    - 5.2.4
    - 5.2.5
  - dependency-name: ergebnis/composer-normalize
    versions:
    - 2.13.2
    - 2.13.3
  - dependency-name: adodb/adodb-php
    versions:
    - 5.20.19
    - 5.20.20
    - 5.21.0
  - dependency-name: codeception/codeception
    versions:
    - 4.1.16
    - 4.1.17
    - 4.1.18
  - dependency-name: twig/twig
    versions:
    - 3.2.1
    - 3.3.0
  - dependency-name: ergebnis/php-cs-fixer-config
    versions:
    - 2.12.1
    - 2.13.0
  - dependency-name: codeception/module-asserts
    versions:
    - 1.3.1
