/* eslint-disable no-undef */
/// <reference types="jquery" />

/// <reference types="jstree" />
/// <reference types="codemirror" />
interface Window {
  jQuery: typeof jQuery;
  $: typeof jQuery;
  inPopUp: boolean;
  stateObj: Record<string, unknown>;
}
// Generated by https://quicktype.io

interface StateObj {
  serverSide: boolean;
  dir: string;
  in_test: string;
  reload: string;
  method: string;
  subfolder: string;
  path: string;
  query_string: string;
  strconfdropcred: string;
  origin: string;
  url: string;
  dttFields: null;
  href: string;
  guessedSubfolder: string;
  pathname: string;
  dttArgs: DataTables.Settings;
  basePath: string;
  realurl: string;
  redirect_to: string;
  parenturl: string;
  dataTable: DataTables.Api;
}

 
declare var stateObj: StateObj;
