checks:
    php:
        code_rating: true
        duplication: true
        variable_existence: true
        useless_calls: true
        use_statement_alias_conflict: true
        unused_variables: true
        unused_properties: true
        unused_parameters: true
        unused_methods: true
        unreachable_code: true
        sql_injection_vulnerabilities: true
        security_vulnerabilities: true
        precedence_mistakes: true
        precedence_in_conditions: true
        parameter_non_unique: true
        no_property_on_interface: true
        no_non_implemented_abstract_methods: true
        deprecated_code_usage: true
        closure_use_not_conflicting: true
        closure_use_modifiable: true
        avoid_useless_overridden_methods: true
        avoid_conflicting_incrementers: true
        assignment_of_null_return: true
        verify_property_names: true
        verify_argument_usable_as_reference: true
        verify_access_scope_valid: true
        use_self_instead_of_fqcn: true
        symfony_request_injection: true
        switch_fallthrough_commented: true
        spacing_of_function_arguments: true
        spacing_around_non_conditional_operators: true
        spacing_around_conditional_operators: true
        space_after_cast: true
        single_namespace_per_use: true
        simplify_boolean_return: true
        scope_indentation:
            spaces_per_level: '4'
        return_doc_comments: true
        require_scope_for_properties: true
        require_scope_for_methods: true
        require_php_tag_first: true
        require_braces_around_control_structures: true
        remove_trailing_whitespace: true
        remove_php_closing_tag: true
        remove_extra_empty_lines: true
        psr2_switch_declaration: true
        psr2_control_structure_declaration: true
        psr2_class_declaration: true
        property_assignments: true
        properties_in_camelcaps: true
        prefer_while_loop_over_for_loop: true
        phpunit_assertions: true
        php5_style_constructor: true
        parameters_in_camelcaps: true
        parameter_doc_comments: true
        return_doc_comment_if_not_inferrable: true
        param_doc_comment_if_not_inferrable: true
        overriding_private_members: true
        optional_parameters_at_the_end: true
        one_class_per_file: true
        non_commented_empty_catch_block: true
        no_unnecessary_if: true
        no_unnecessary_function_call_in_for_loop: true
        no_unnecessary_final_modifier: true
        no_underscore_prefix_in_properties: true
        no_underscore_prefix_in_methods: true
        no_trailing_whitespace: true
        no_space_inside_cast_operator: true
        no_space_before_semicolon: true
        no_space_around_object_operator: true
        no_goto: true
        no_global_keyword: true
        no_exit: true
        no_empty_statements: true
        no_else_if_statements: true
        no_duplicate_arguments: true
        no_debug_code: true
        no_commented_out_code: true
        newline_at_end_of_file: true
        fix_php_opening_tag: true
        no_mixed_inline_html: false
        avoid_superglobals: false
        check_method_contracts:
            verify_interface_like_constraints: true
            verify_documented_constraints: true
            verify_parent_constraints: true
        no_short_method_names:
            minimum: '3'
        too_many_arguments: false
    javascript: true
filter:
    paths: [src/*]
    excluded_paths:
        - '.tests/*'
        - 'tests/*'
        - '*.min.js'
        - 'js/'

tools:
    php_analyzer: true
    php_mess_detector: true
    php_changetracking: true
    php_cs_fixer:
        config: { level: psr2 }
    php_code_sniffer:
        config:
            standard: PSR2
    php_loc:
        excluded_dirs:
            - vendor
    php_pdepend:
        excluded_dirs:
            - vendor
            - tests
            - .tests
      
build:
    environment:
        php: '7.1'
    tests:
        override:
          - 'php-scrutinizer-run'
          - 'phpcs-run ./src/'
          - 'php vendor/bin/codecept run unit'
    nodes:
        tests: true
        analysis:
            tests:
                override:
                    - 
                        command: phpcs-run
                        use_website_config: true