checks:
    php:
        code_rating: true
        duplication: true
        fix_php_opening_tag: true
        remove_php_closing_tag: true
        no_mixed_inline_html: false
        require_braces_around_control_structures: true
        psr2_control_structure_declaration: true
        avoid_superglobals: false
        security_vulnerabilities: true
        no_exit: true
        simplify_boolean_return: true
        return_doc_comments: false
        return_doc_comment_if_not_inferrable: false
        remove_extra_empty_lines: true
        parameter_doc_comments: false
        check_method_contracts:
            verify_interface_like_constraints: true
            verify_documented_constraints: true
            verify_parent_constraints: true
        no_short_method_names:
            minimum: '3'
        too_many_arguments: false
        no_goto: true
        fix_use_statements:
            remove_unused: true
            preserve_multiple: false
            preserve_blanklines: false
            order_alphabetically: false
        fix_line_ending: true
filter:
    paths: 
        - 'src/*'
    excluded_paths:
        - '.tests/*'
        - 'tests/*'
        - '*.min.js'
        - 'js/'
tools:
    php_code_sniffer:
        config:
            standard: PSR2
        filter:
            paths: ['src']
build:
    environment:
        php: '7.1'
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
                    - 'make test'

        tests: true