preset: recommended
risky: true
enabled:
  - align_equals

disabled:
  - unalign_equals

finder:
  exclude:
    - modules
    - node_modules
    - storage
    - vendor
  name: "*.php"
  not-name: "*.blade.php"
