name: Rector Checkstyle
'on':
  push:
    branches:
      - master
      - develop


env:
  MIN_COVERED_MSI: 100
  MIN_MSI: 100
  PHP_EXTENSIONS: "mbstring, pgsql"
  key: cache-v1 # can be any string, change to clear the extension cache.
      
jobs:
  rector_checkstyle:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version:
          - "7.3"
        dependencies:
          - "locked"
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
      - uses: n1hility/cancel-previous-runs@v2
        with:
          token: '${{ secrets.GH_ACTIONS_TOKEN }}'
      - name: Setup cache environment
        id: extcache
        uses: shivammathur/cache-extensions@v1
        with:
          php-version: '${{ matrix.php_version }}'
          extensions: '${{ env.PHP_EXTENSIONS }}'
          key: '${{ env.key }}'
      - name: Cache extensions
        uses: actions/cache@v2.1.1
        with:
          path: '${{ steps.extcache.outputs.dir }}'
          key: '${{ steps.extcache.outputs.key }}'
          restore-keys: '${{ steps.extcache.outputs.key }}'


      - name: Install locked dependencies from composer.lock
        run: composer install --no-interaction --no-progress --no-suggest
      - name: Create dummy config files
        run: cp config.inc.php-dist config.inc.php

      - name: Install PHP with extensions
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          extensions: '${{ env.PHP_EXTENSIONS }}'
          php-version: '${{ matrix.php_version }}'
          tools: 'composer, cs2pr'

      - name: Cache Composer
        uses: "actions/cache@v2.1.1"
        with:
          path: "~/.composer/cache"
          key: "composer-${{ hashFiles('composer.lock') }}"
          restore-keys: "composer-"
  
      - name: "Install locked dependencies from composer.lock"
        run: "composer install --no-interaction --no-progress --no-suggest"

      - name: "Create cache folder for rector"
        run: "mkdir -p .build/rector"
   
      - name: "Cache cache directory for rector"
        uses: "actions/cache@v2.1.1"
        with:
          path: ".build/rector"
          key: "php-${{ matrix.php_version }}-rector-${{ github.sha }}"
          restore-keys: "php-${{ matrix.php_version }}-rector-"

      - run: >-
          vendor/bin/rector process --ansi --dry-run --output-format=checkstyle
          | cs2pr
